# Generated by Django 4.2 on 2023-04-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='my_view',
            field=models.CharField(default=2, max_length=202),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='publication date'),
        ),
    ]
