# Generated by Django 4.2 on 2023-04-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choices_my_view_alter_questions_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(verbose_name='publication date'),
        ),
    ]
