# Generated by Django 4.2 on 2023-04-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_questions_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='my_view',
        ),
    ]
